### PR TITLE
Improve Testing in PR

### PR DESCRIPTION
**Pull request by Skisocks**
Looks like GITHUB_TOKEN isn't actually passed in the pipelines, think jx-helpers was actually pulling it from the credentials file or something. Will look into supporting this, but for the time being I'll just add the token as an env var. 

* Installing Peacock from make in PR to test latest version
* Throwing an error if Github token isn't passed

### CODE REVIEW

**Review by tomhobson — APPROVED** [review]

**Comment by tomhobson** [comment]
Peacock-ception

**Comment by Skisocks** [comment]
?

**Pull request merged**
